### ISSUE TITLE
Status getMillis method is not correct

### ISSUE THREAD

**Issue by colinfkennedy** [aol/simple-react#28]
Currently it will return your Nano seconds * 10000000, but it should be a divide.        
        public final long getElapsedMillis(){
		return elapsedNanos / 1000000;
	}

Although, this will give you a rounding error, which may or may not matter.

**Comment by johnmcclean-aol** [comment]
Good spot - pull request ?

**Comment by colinfkennedy** [comment]
Sure. Do you care about the rounding error?

**Comment by johnmcclean-aol** [comment]
Not 100% sure, but I think if users want that level of accuracy they will probably go with the nanos. So the simpler solution is best.
