### ISSUE TITLE
SimpleReact creation methods return the Base class rather than SimpleReactStream

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/simple-react#88]
SimpleReact fromIterable (etc) should return SimpleReactStream

**Comment by Zeouterlimits** [comment]
Merged - https://github.com/aol/simple-react/commit/22a62912f049eeb256f9c3067d573fbe1e919f56

**Comment by johnmcclean-aol** [comment]
Closed - https://github.com/aol/simple-react/pull/93
