### ISSUE TITLE
Make shuffle lazy / intermediate operation

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/simple-react#99]
Current shuffle implementation consumes the stream before shuffling. A reasonable compromise would be to group by some largeish number before before shuffling that collection, followed by flattening to a single traversable again.

**Comment by lukaseder** [comment]
I had thought about this, too, when implementing `Seq.shuffle()`, but is that sufficiently random for most cases? E.g. how often do you get a corner case where a "largish" number of A values precede a "largish" number of B values?

**Comment by johnmcclean-aol** [comment]
Good point - there probably isn't a perfect solution to this (at least I can't think of one yet). A new operator (or two equivalents for shuffle() and shuffle(random)) might help - e.g. 

``java
public Seq<T> shuffle(long shuffleGroupSize);
```
Which would leave the question as to whether shuffle() should be intermediate with a default batch size, or consume the Stream?

There are limitations with infinite Streams if we consume the whole stream before shuffling - but also other challenges remain even with grouping e.g.

```java
(Reactive)Seq.generate(this::nextElement()).shuffle().limit(100);
```
Ideally the limit should be applied to the group size within shuffle also (so we don't generate more than 100 elements), but I suspect the cost / benefit of implementing that kind of logic is not worth it.

It's mentioned in a blog post here by the way -> https://habrahabr.ru/post/262139/

**Comment by lukaseder** [comment]
> There are limitations with infinite Streams if we consume the whole stream before shuffling

Indeed, shuffle doesn't make sense (or at least, it's dangerous) with infinite streams. But then again, the same is true for vanilla JDK's `Stream.distinct()` or `Stream.sorted()`. Both are not possible to implement accurately without buffering the entire stream, see for instance `java.util.stream.SortedOps.RefSortingSink`, which collects the entire "upstream" into an `ArrayList`. The question is really how much we value accuracy for `shuffle()`.

> It's mentioned in a blog post here by the way -> https://habrahabr.ru/post/262139/

Yes, I've seen that. @amaembo keeps trying desperately to get more stars than jOOλ for his https://github.com/amaembo/streamex library ;-)

**Comment by lukaseder** [comment]
> The problem with jOOλ shuffle (as well as with some other operations) is that they are absolutely eager. 

Huh, you're right! This should be easy to implement lazily, though. Will fix. Thanks for the feedback!

> Probably it's not important for jOOλ and simple-react.

It is important, and it's an oversight.

> @lukaseder named such thingy as transform()

Big Brother is watching me! :)

**Comment by danieldietrich** [comment]
@lukaseder @amaembo you are not alone 👽 too many throwing function and stream extensions here at github

**Comment by johnmcclean-aol** [comment]
It's simple enough to shuffle within a flatMap operator after grouping, so I think this is a reasonable approach - https://github.com/jOOQ/jOOL/issues/195

I'll close it this issue and keep an eye on the jOOλ one, I can have a crack at implementing it if you like?

Thanks for your input guys! @lukaseder  @amaembo @danieldietrich

**Comment by lukaseder** [comment]
> I can have a crack at implementing it if you like?

Of course! :) Very appreciated!
